#!/bin/bash
set -e

cd "$(dirname "$0")/.."

# Build the tuner
cmake -S . -B build
cmake --build build --target tune_pst

# Default PGN file
PGN="${1:-data/lichess_elite.pgn}"

if [ ! -f "$PGN" ]; then
    echo "Error: PGN file not found: $PGN"
    echo "Usage: $0 [pgn_file]"
    exit 1
fi

echo "Generating PST from: $PGN"

# Generate PST tables with header
{
    echo "#pragma once"
    echo ""
    echo "// Auto-generated by scripts/gen_pst.sh"
    echo "// Source: $PGN"
    echo ""
    ./build/tune_pst "$PGN" \
        -K 400 \
        -lr 200 \
        -epochs 5000 \
        -min-elo 2200 \
        -min-time 100 \
        -skip 8 \
        -report 100 \
        -max-pos 5000000
} > src/pst_tables.hpp

echo ""
echo "Generated src/pst_tables.hpp"
